### ISSUE TITLE
🐛 Bug: no parser for `typescriptreact` language

### ISSUE THREAD

**Issue by mobily** [Dkendal/nvim-treeclimber#2]
hello, @Dkendal 👋 nice plugin! however, there is an error when getting a parser for specific filenames, for example, when using the plugin in `typescriptreact` files (which belongs to the `typescript` parser) I got the following error:

<img width="1412" alt="CleanShot 2022-11-24 at 09 47 25@2x" src="https://user-images.githubusercontent.com/1467712/203735618-ddeea81c-a818-4e39-a029-ee06721ca95c.png">

**Comment by Dkendal** [comment]
Thanks for the report @mobily! I'll take a look at this today, as well as the general case of a parser missing :)

**Comment by mobily** [comment]
@Dkendal it works perfectly, thanks so much! 🚀
